config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get '/list', to: 'users#list'


  # ユーザーデータのコントローラ
  get '/0x2d0r31/v1/user/list', to: "users#index", as: 'user_list'

  # 詳細画面へ
  get "/0x2d0r31/v1/user/:id", to: "users#show", as: 'user_show'

  #　凍結
  get "/0x2d0r31/v1/user/:userId/:itemId/suspend", to: "users#suspend"
  post "/0x2d0r31/v1/user/:userId/:itemId/suspend", to: "users#suspend", as: 'user_suspend'

  # 作成
  # indexからgetで取得する
  get "/xy76Za109b/v1/user/create", to: "users#new", as: 'move_user_create'
  post "/xy76Za109b/v1/user/create", to: "users#create", as: 'post_user_create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/banner.rb
class Banner < ApplicationRecord
end

app/models/platform.rb
class Platform < ApplicationRecord
    self.primary_key = 'platformId'
    belongs_to :user_platform, primary_key: :platformId, foreign_key: :platformId
    belongs_to :user_platform, primary_key: :platformName, foreign_key: :platformName
end


# 親
# has_many :子のテーブル名, primary_key: :親の主キー, foreign_key: :親の主キー

# 子
# belongs_to :親のテーブル名, primary_key: :親の主キー, foreign_key: :親の主キー

app/models/user.rb
class User < ApplicationRecord
    validates :hashtag, uniqueness: true
    validates :hashtag, numericality: {only_integer: true}

    self.primary_key = 'userId'
    has_many :user_meta_names, primary_key: :userId, foreign_key: 'userId', class_name: 'UserMetaName'
    has_many :user_platforms, primary_key: :userId, foreign_key: 'userId', class_name: 'UserPlatform'

    accepts_nested_attributes_for :user_meta_names, allow_destroy: true
    accepts_nested_attributes_for :user_platforms, allow_destroy: true
end

app/models/user_meta_name.rb
class UserMetaName < ApplicationRecord
    belongs_to :user, primary_key: :userId, foreign_key: :userId, optional: true
end

# 親
# has_many :子のテーブル名, primary_key: :親の主キー, foreign_key: :親の主キー

# 子
# belongs_to :親のテーブル名, primary_key:  :親の主キー, foreign_key: :親の主キー,

app/models/user_platform.rb
class UserPlatform < ApplicationRecord
    validates :accountUserUrl, format: /\A#{URI::regexp(%w(http https))}\z/
    validates :accountIconImageUrl, format: /\A#{URI::regexp(%w(http https))}\z/

    belongs_to :user, primary_key: :userId, foreign_key: 'userId', optional: true
    has_many :platforms, primary_key: :platformId, foreign_key: 'platformId'
    has_many :platforms, primary_key: :platformName, foreign_key: 'platformName'
end

# 親
# has_many :子のテーブル名, primary_key: :親の主キー, foreign_key: :親の主キー

# 子
# belongs_to :親のテーブル名, primary_key: :親の主キー, foreign_key: :親の主キー

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def list
      users = User.includes(:user_meta_names, :user_platforms)

      shuffled_users =  users.shuffle
  
      users_with_meta = shuffled_users.map do |user|
        {
          userId: user.userId,
          hashtag: '#' + user.hashtag,
          name: user.name,
          metaNames: user.user_meta_names.map(&:userMetaName),
          userPlatforms: user.user_platforms.map do |up|
            if up.hasAccount == true 
              {
                itemId: up.itemId,
                platformId: up.platformId,
                platformName: up.platformName,
                accountUserId: up.accountUserId,
                accountUserName: up.accountUserName,
                accountIconImageUrl: up.accountIconImageUrl,
                accountUserUrl: up.accountUserUrl,
                accountUserSubText: '@' + up.accountUserSubText,
                hasAccount: up.hasAccount,
                isBroadCasting: up.isBroadCasting
              }
            else 
              {
                itemId: up.itemId,
                hasAccount: false
              }
            end
          end
        }
      end
  
      pretty_json = JSON.pretty_generate(users_with_meta)
      render plain: pretty_json
    end

    def index
      @users = User.all
      render :layout => "layouts/application"
    end

    def show
      @user = User.find_by(userId: params[:id])
      render :layout => "layouts/application"
    end

    def suspend
      @user = User.find_by(userId: params[:userId])
      @item = @user.user_platforms.find_by(itemId: params[:itemId])
      @item.hasAccount = @item.hasAccount ? false : true
      @item.save
      @user.save
      @users = User.all

      redirect_to user_list_path
    end

    def new
      @user = User.new
      @user.user_meta_names.build
      @user.user_platforms.build
      @platforms = Platform.all
      render :layout => "layouts/application"
    end

    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to user_list_path
      else
        @platforms = Platform.all
        render :new, layout: "layouts/application"
      end
    end

    private

    def user_params
      params.require(:user).permit(
        :name, :hashtag,
        user_meta_name_attributes: [:userMetaNames],
        user_platforms_attributes: [
          :id,
          :itemId,
          :accountUserId, 
          :accountUserName, 
          :accountIconImageUrl, 
          :accountUserUrl, 
          :accountUserSubText, 
          :hasAccount, 
          :isBroadCasting, 
          :platformId,
          :platformName
        ]
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/get_helper.rb
module GetHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NiconicoResearcherApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', type: "module", 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <script>
    $(function(){
      $('.dropdown-menu .dropdown-item').click(function(){
          var visibleItem = $('.dropdown-toggle', $(this).closest('.dropdown'));
          visibleItem.text($(this).attr('value'));
      });
  });
    </script>
  </head>

  <body>
  <%= yield %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/index.html.erb
<div class = "container">
  <div style="display: flex;">
    <%= link_to "ユーザー登録する", move_user_create_path, class: "btn btn-warning" %>
    <div class="mb-9">
      <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
    </div>
    <button type="button" class="btn btn-success">検索</button>

    <button type="button" class="btn btn-info ml-3">APIを使ってデータを更新する</button>
  </div>

  <div class="table-responsive">
    <table class="table table-dark table-striped-columns table-hover  table-sm" style="white-space: nowrap;">
    <th class="table-secondary">
          <tr>
            <td>
              ID
            </td>
            <td>
              #
            </td>
            <td>
              名前
            </td>
            <td>
              配信場所
            </td>
            <td>
              アカウントID
            </td>
            <td>
              アカウント名
            </td>
            <td>
              表示用テキスト
            </td>
            <td>
              URL
            </td>
            <td>
              放送中？
            </td>
            <td>
              アカウント状況
            </td>
            <td>
              アクション
            </td>
            </tr>
        </th>
        <% @users.each do |u| %>
          <% u.user_platforms.each do |us| %>
            <tr>
              <td>
                <%= us.itemId %>
              </td>
              <td>
                <%= u.hashtag %>
              </td>
              <td>
                <%= u.name %>
              </td>
              <td>
                <%= us.platformName %>
              </td>
              <td>
                <%= us.accountUserName %>
              </td>
              <td>
                <%= us.accountUserName %>
              </td>
              <td>
                <%= us.accountUserSubText %>
              </td>
              <td>
                <button type="button" class="btn btn-link">
                  <%= link_to us.accountUserUrl, us.accountUserUrl, target: :_blank, rel: "noopener noreferrer" %>
                </button>
              </td>
              <td>
                <% if us.isBroadCasting == true %>
                  <button type="button" class="btn btn-outline-danger">配信中</button>
                <% end %>
              </td>
              <td>
                <% if us.hasAccount == false %>
                　<button type="button" class="btn btn-outline-info">凍結済</button>
                <% end %>
              </td>
              <td>
                <%= link_to "編集", user_show_path(id: u.userId), class: "btn btn-primary" %>
                <% if us.hasAccount == true %>
                  <%= link_to "非公開", user_suspend_path(userId: u.userId, itemId: us.itemId), method: :post, class: "btn btn-warning" %>
                <% elsif us.hasAccount == false %>
                  <%= link_to "公開", user_suspend_path(userId: u.userId, itemId: us.itemId), method: :post, class: "btn btn-info" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% end %>
    </table>
  </div>

  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-end">
      <li class="page-item disabled">
        <a class="page-link">Previous</a>
      </li>
      <li class="page-item active"><a class="page-link" href="#">1</a></li>
      <li class="page-item"><a class="page-link" href="#">2</a></li>
      <li class="page-item"><a class="page-link" href="#">3</a></li>
      <li class="page-item">
        <a class="page-link" href="#">Next</a>
      </li>
    </ul>
  </nav>
</div>

app/views/users/new.html.erb
<%= form_with model: @user, local: true do |f| %>
    <div class="container">
        <h4 class="mt-5 mb-5">
            <b>ユーザー新規作成</b> 
        </h4>
        <% if @user.errors.any? %>
            <div id="error_explanation" class="alert alert-danger">
            <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
            <ul>
                <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
            </ul>
            </div>
        <% end %>
        <table class="table">
            <tbody>
                <tr>
                    <td scope="row" style="width: 30%">ユーザーID(編集不可)</td>
                    <td>
                        8
                        <%= f.hidden_field :userId, :value => '9' %>
                    </td>
                </tr>
                <tr>
                    <td scope="row" style="width: 30%">ユーザーネーム</td>
                    <td>
                        <%= f.text_field :name, class: "form-control" %>
                    </td>
                </tr>
                <tr>
                    <td scope="row" style="width: 30%">ハッシュ番号</td>
                    <td>
                        <%= f.text_field :hashtag, class: "form-control" %>
                    </td>
                </tr>
                <tr>
                    <td scope="row" style="width: 30%">メタタグ</td>
                    <td>
                        <%= f.fields_for :user_meta_names do |meta_form| %>
                            <%= meta_form.text_field :userMetaName, class: "form-control" %>
                        <% end %>
                    </td>
                </tr>
                
            </tbody>
        </table>
    </div>

    <div class="container mt-5">
        <table class="table">
            <tbody>
            <%= f.fields_for :user_platforms do |platform_form| %>
                <tr>
                    <td scope="row" style="width: 30%">アイテムID(編集不可)</td>
                    <td>
                        8
                        <%= f.hidden_field :userId, :value => '9' %>
                    </td>
                </tr>
                <tr>
                    <td scope="row" style="width: 30%">プラットフォーム</td>
                    <td>
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                プラットフォームを選択
                            </button>
                            <ul class="dropdown-menu">
                                <li><button class="dropdown-item" value="1">1. Twitch</button></li>
                                <li><button class="dropdown-item" value="2">2. ふわっち</button></li>
                                <li><button class="dropdown-item" value="3">3. ツイキャス</button></li>
                                <li><button class="dropdown-item" value="4">4. YouTubeLive</button></li>
                                <li><button class="dropdown-item" value="5">5. LINEオープンチャット</button></li>
                                <li><button class="dropdown-item" value="6">6. X</button></li>
                                <li><button class="dropdown-item" value="7">7. Instagram</button></li>
                                <li><button class="dropdown-item" value="8">8. TikTok</button></li>
                                <li><button class="dropdown-item" value="9">9. OpenRec</button></li>
                                <li><button class="dropdown-item" value="10">999. その他</button></li>
                            </ul>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td scope="row" style="width: 30%">ユーザーID（Twitchのみ）</td>
                    <td>
                        <%= platform_form.text_field :accountUserId, class: "form-control" %>
                    </td>
                </tr>
                <tr>
                    <td scope="row" style="width: 30%">アカウント名</td>
                    <td>
                        <%= platform_form.text_field :accountUserName, class: "form-control" %>
                    </td>
                </tr>
                <tr>
                    <td scope="row" style="width: 30%">アカウントURL</td>
                    <td>
                        <%= platform_form.text_field :accountUserUrl, class: "form-control" %>
                    </td>
                </tr>
                <tr>
                    <td scope="row" style="width: 30%">表示するIDテキスト</td>
                    <td>
                        <%= platform_form.text_field :accountUserSubText, class: "form-control" %>
                    </td>
                </tr>
                <tr>
                    <td scope="row" style="width: 30%">アカウントアイコン画像URL</td>
                    <td>
                        <%= platform_form.text_field :accountIconImageUrl, class: "form-control" %>
                    </td>
                </tr>
            </tbody>
        </table>
        <%= platform_form.hidden_field :itemId, :value => "15" %>
        <%= platform_form.hidden_field :hasAccount, :value => "true" %>
        <%= platform_form.hidden_field :isBroadCasting, :value => "false" %>
    <% end %>
</div>

<div class="container mt-5 mb-5">
<div class="d-grid gap-2">
    <%= f.submit "この内容で登録する", class: "btn btn-success" %>
    <button class="btn btn-primary" type="button">入力作業を続ける</button>
    <%= link_to '破棄する', :back, class: "btn btn-secondary" %>
</div>
</div>
<% end %>

app/views/users/show.html.erb
<div class="container">
    <h4 class="mt-5 mb-5">
        <b><%= @user.name %></b> 
    </h4>
    <table class="table table-dark table-striped-columns table-hover  table-sm" style="overflow: scroll;">
    <th class="table-secondary">
        <% @user.user_platforms.each do |us| %>
        <tr>
            <td>
            <%= us.itemId %>
            </td>
            <td>
            <%= @user.hashtag %>
            </td>
            <td>
            <%= @user.name %>
            </td>
            <td>
            <%= us.platformName %>
            </td>
            <td>
            <%= us.accountUserName %>
            </td>
            <td>
            <%= us.accountUserName %>
            </td>
            <td>
            <%= us.accountUserSubText %>
            </td>
            <td>
            <button type="button" class="btn btn-link">
                <%= link_to us.accountUserUrl, us.accountUserUrl, target: :_blank, rel: "noopener noreferrer" %>
            </button>
            </td>
            <td>
            <% if us.isBroadCasting == true %>
                <button type="button" class="btn btn-outline-danger">配信中</button>
            <% end %>
            </td>
            <td>
            <% if us.hasAccount == false %>
            　<button type="button" class="btn btn-outline-info">凍結済</button>
            <% end %>
            </td>
            <td>
            <button type="button" class="btn btn-primary">編集</button>
            <% if us.hasAccount == true %>
                <button type="button" class="btn btn-warning">非公開</button>
            <% end %>
            </td>
        </tr>
        <% end %>
    </table>

    <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-end">
    <li class="page-item disabled">
        <a class="page-link">Previous</a>
    </li>
    <li class="page-item active"><a class="page-link" href="#">1</a></li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
    <li class="page-item">
        <a class="page-link" href="#">Next</a>
    </li>
    </ul>
    </nav>

</div>